<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Katalon TestOps</name>
   <tag></tag>
   <elementGuidId>c2e31f17-9afc-4549-b399-7ffdabad650e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.section-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>c6659d79-5610-4e5e-87a3-5ce051e5730e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-title</value>
      <webElementGuid>28708052-6aad-41c4-93c1-7d695aeeaca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon TestOps</value>
      <webElementGuid>9c245c36-eb2f-4db6-954a-d547722b0e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;TestOps_wrappingTestOps__GzKRz&quot;]/div[@class=&quot;testops&quot;]/div[@class=&quot;hero&quot;]/div[@class=&quot;content&quot;]/h1[@class=&quot;section-title&quot;]</value>
      <webElementGuid>ac0b644d-f434-4bd1-b059-0d6f003ebceb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div/div/h1</value>
      <webElementGuid>b2a13d95-36a2-4c4a-8865-4b9c8fd415f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All jobs'])[2]/following::h1[1]</value>
      <webElementGuid>1130da07-5168-44b4-bcbb-f279053fbace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Being here'])[2]/following::h1[1]</value>
      <webElementGuid>49ac5ffe-ae45-47c6-b60a-a9cf84a1dc78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orchestrate Tests. Connect DevOps. Act on Insights'])[1]/preceding::h1[1]</value>
      <webElementGuid>d144ad97-2759-4a1a-8ce3-0a045c08f904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start for free'])[1]/preceding::h1[1]</value>
      <webElementGuid>3cf8a70c-354a-4210-b821-4c43fa4161dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>93251084-0d08-4e2c-9de7-bb6d2d4612cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Katalon TestOps' or . = 'Katalon TestOps')]</value>
      <webElementGuid>095c2a15-bdbd-4891-a1f6-b87c19cbc78e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
